services:
  tts:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./outputs:/app/outputs
      - ./piper_models:/app/piper_models
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '${WORKERS:-4}'
          memory: ${MEMEORY:-2G}
    restart: always