services:
  tts:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
    deploy:
      resources:
        limits:
          cpus: '${WORKERS:-4}'
          memory: ${MEMEORY:-2G}
    restart: always